<?php

// Load Field module hooks.
//module_load_include('inc', 'bibdk_linkme', 'bibdk_linkme.field');

/**
 * Implements hook_menu
 */
function bibdk_adhl_menu(){
  $items['overlay/adhl/%'] = array(
    'title' => t('Recommendations', array(), array('context' => 'bibdk_adhl')),
    'page callback' => 'bibdk_adhl_get_adhl_info',
    'page arguments' => array('id' => 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['adhl/ajax'] = array(
    'page callback' => 'bibdk_adhl_ajax_get_recommendations',
    #'page arguments' => array('id' => 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'bibdk_adhl.ajax.inc',
  );
  return $items;
}

/**
 * Show list of recommendations
 * @param $pid
 * @return string
 */
function bibdk_adhl_get_adhl_info($pid){
  //TODO: numresults should be a setting
  $result = bibdk_adhl_request($pid, 10);
  if (!$result){
    drupal_set_message(t('no_recommendations'), 'warning');
    return "";
  }
  return bibdk_adhl_get_list($result);
}

/**
 * execute adhl request
 * @param $pid
 * @param int $numResults
 * @return array
 */
function bibdk_adhl_request ($pid, $numResults = 3){
  /**
   * Client needs to be rewritten to recieve and return pid's
   */
  /*
  $client = new ting_client_class();
  $param = array(
    'pid' => $pid,
    'numResults' => $numResults,
  );
  $result = $client->do_adhl($param);*/

  //this is just dummy content for test and development
  return array('870970-basis:21905208', '870970-basis%3A26917921');
}

/**
 * Return a list of links from a list of pid's
 * @param $pids
 * @return string html formatted list of links
 */
function bibdk_adhl_get_list($pids) {
  /**
   * ting_openformat_get_manifestations returns a bibdkWork as an array and all
   * the manifestations are saved in the manifestations variable.
   * TODO :ting_openformat should have a method to return an array of manifestations
   */
  $works = ting_openformat_get_manifestations($pids);
  $work = reset($works);

  foreach($work->manifestations as $id => $manifestation){
    $links[] = array(
      'title' => $manifestation->getTitle(),
      'href'  => 'work/'.$id,
    );
  }
  return theme('links', array(
    'links' => $links,
  ));

}

